-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgaj17uoVjl4MkZIjx
kATPiDZ4Ei9bA6EOciXklwhhHDygCgYIKoZIzj0DAQehRANCAAQnyBaNraUfeet8
Nf/u5k235a4INjBP48G+N1XzwvT0o/HCeScaGuPhZgEr2rB+3IXmgxzzi3lNWpf3
Vpw+AtKE
-----END PRIVATE KEY-----